# Generated by Django 5.0.2 on 2024-02-12 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_index',
            new_name='question_text',
        ),
    ]
